name: Build Kernel with Docker Support
on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@v1.2
        with:
          kernel-url: https://github.com/a358800298/android_kernel_xiaomi_sdm845
          kernel-branch: lineage-21
          config: vendor/sdm845-perf_defconfig
          arch: arm64
          android-version: 14
          lxc: true
          aosp-clang: true
          aosp-gcc: false
